### ISSUE TITLE
Compatibility Issue Between MAS Static Content and ACF Plugin in WooCommerce Product Descriptions

### ISSUE THREAD

**Issue by vocus07** [madrasthemes/mas-static-content#14]
I recently updated the plugin to version 1.0.5 and noticed that Mass Static Content no longer works with the ACF plugin, but only if the ACF fields are used in product descriptions in WooCommerce. However, when I downgraded back to version 1.0.4, everything works correctly again.

Could you please investigate this issue and provide a solution or workaround as soon as possible? I rely heavily on both plugins for my website's functionality, and this compatibility issue is causing significant disruption.

Thank you for your attention to this matter.

**Comment by subaida77** [comment]
Hello there, Apologies for our delayed response. We've not been monitoring our GitHub repo for support issues. Can you please provide us with the step-by-step instruction to reproduce the issue? Thank you.

**Comment by vocus07** [comment]
Hello, yes if I add ACF field to mass static for example `[acf
field="field_name"]` it's doesn't show properly.

czw., 25 sty 2024 o 16:36 Subaida Begum ***@***.***>
napisał(a):

**Comment by subaida77** [comment]
Hello there, thank you for your clarification. We are working on this issue. We shall update you as soon as possible on this.

**Comment by subaida77** [comment]
Hello again, We've implemented this feature. You can now use the ACF field shortcode from the calling post like this: 
```
[acf field="name" post_id="inherit"]
```
